config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'

  #get '/home', to: 'pages#home'
  #get '/recipes', to: 'recipes#index'
  #get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
  #post '/recipes', to: 'recipes#create'
  #get '/recipes/:id/edit', to: 'recipes#edit', as: 'edit_recipe'
  #patch '/recipes/:id', to: 'recipes#update'
  #get '/recipes/:id', to: 'recipes#show', as: 'recipe'
  #delete '/recipes/:id', to: 'recipes#destroy'
  
  resources :recipes do
    member do
      post 'like'
    end
  end
  
  resources :chefs, except: [:new]
  get '/register', to: 'chefs#new'
  
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]
  
end

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to MyRecipes App</h1>
  <h2>This is the professional Ruby on Rails course on Udemy by Mashrur</h2>
  <%= link_to "Sign me up!", register_path, class: "btn btn-lg btn-success" %>
</div>
<div class="row">
  <div class="col-md-4">
    <div class="midrow">
      <h3>View Recipes as Guest User</h3>
      <h2>View recipes as a guest user and sign up later</h2>
      <p><%= link_to "View recipe listing", recipes_path, class: "btn btn-small btn-warning" %></p>
    </div>
  </div>
  
  <div class="col-md-4">
    <div class="midrow">
      <h3>Sign in to your account</h3>
      <h2>Add/update your recipes/create reviews/like-dislike recipes and much more...</h2>
      <p><%= link_to "Log in to your account", login_path, class: "btn btn-small btn-warning" %></p>
    </div>
  </div>
  
  <div class="col-md-4">
    <div class="midrow">
      <h3>View Recipes as Guest User</h3>
      <h2>View recipes as a guest user and sign up later</h2>
      <p><%= link_to "View recipe listing", "", class: "btn btn-small btn-warning" %></p>
    </div>
  </div>
  
</div>